---
- name: Configure VIP LB
  import_tasks: lb.yaml

- name: Configure HA ETDC
  import_tasks: etcd.yaml

- name: Wait for Kube master
  wait_for:
    path: /etc/environment
    search_regex: "KUBECONFIG=/etc/kubernetes/admin.conf"
  delegate_to: "{{kube_server}}"

- name: Add node to kube cluster control_plane
  command: kubeadm join --control-plane --token {{kube_token}} {{kube_control_plane_ip}}:{{kube_control_plane_port}} --discovery-token-unsafe-skip-ca-verification --ignore-preflight-errors=all creates=/etc/kubernetes/admin.conf