---
- name: Add NVIDIA PPA
  apt_repository:
    repo: ppa:graphics-drivers/ppa
    update_cache: yes

- name: Install nvidia-driver package
  apt: name=nvidia-driver-{{ kube_nvidia_driver_version }}
  when: ansible_distribution_major_version|int >= 18

- name: Install nvidia package
  apt: name=nvidia-{{ kube_nvidia_driver_version }}
  when: ansible_distribution_major_version|int == 16

- block:

    - name: Add nvidia-docker repo key
      apt_key:
        url: "https://nvidia.github.io/nvidia-docker/gpgkey"
        state: present

    - name: Download nvidia-docker apt list
      get_url:
        url: https://nvidia.github.io/nvidia-docker/{{ansible_distribution | lower}}{{ansible_distribution_version}}/nvidia-docker.list
        dest: /etc/apt/sources.list.d/nvidia-docker.list

    - name: Ubuntu apt update
      apt: update_cache=yes

    - name: Install nvidia-docker2 package
      apt: name=nvidia-docker2
      notify: restart docker

    - copy:
        dest: /etc/docker/daemon.json
        content: |
            {
                "default-runtime": "nvidia",
                "runtimes": {
                    "nvidia": {
                        "path": "/usr/bin/nvidia-container-runtime",
                        "runtimeArgs": []
                    }
                }
            }
      notify: restart docker

  when: kube_cri_runtime == "docker"

- block:

    - name: Add nvidia-container repo key
      apt_key:
        url: "https://nvidia.github.io/nvidia-container-runtime/gpgkey"
        state: present

    - name: Download nvidia-container apt list
      get_url:
        url: https://nvidia.github.io/nvidia-container-runtime{{ansible_distribution | lower}}{{ansible_distribution_version}}/nvidia-container-runtime.list
        dest: /etc/apt/sources.list.d/nvidia-container-runtime.list

    - name: Ubuntu apt update
      apt: update_cache=yes

    - name: Install nvidia-container package
      apt: name=nvidia-container-runtime 
      notify: restart containerd

    - name: Change runtime to nvidia-container-runtime
      lineinfile:
        path: /etc/containerd/config.toml
        regexp: '^(.*)runtime = "runc"(.*)$'
        line: '\1runtime = "nvidia-container-runtime"\2'
        backrefs: yes
      notify: restart containerd

  when: kube_cri_runtime == "containerd"

