---
- name: Add NVIDIA PPA
  apt_repository:
    repo: ppa:graphics-drivers/ppa
    update_cache: yes

- name: Install nvidia-driver package
  apt: name=nvidia-driver-{{ kube_nvidia_driver_version }}
  when: ansible_distribution_major_version|int >= 18

- name: Install nvidia package
  apt: name=nvidia-{{ kube_nvidia_driver_version }}
  when: ansible_distribution_major_version|int == 16

- name: Include NVIDIA {{kube_cri_runtime}} tasks
  include_tasks: "Debian_nvidia_{{kube_cri_runtime}}.yaml"
