---
- name: Add nvidia-container repo key
  apt_key:
    url: "https://nvidia.github.io/nvidia-container-runtime/gpgkey"
    state: present

- name: Download nvidia-container apt list
  get_url:
    url: https://nvidia.github.io/nvidia-container-runtime/{{ansible_distribution | lower}}{{ansible_distribution_version}}/nvidia-container-runtime.list
    dest: /etc/apt/sources.list.d/nvidia-container-runtime.list

- name: Ubuntu apt update
  apt: update_cache=yes

- name: Install nvidia-container package
  apt: name=nvidia-container-runtime 
  notify: restart containerd

- name: Change runtime to nvidia-container-runtime
  lineinfile:
    path: /etc/containerd/config.toml
    regexp: '^(.*)runtime = "runc"(.*)$'
    line: '\1runtime = "nvidia-container-runtime"\2'
    backrefs: yes
  notify: restart containerd
