---
- set_fact:
    docker_install: true

- name: Check docker version
  shell: docker -v | cut -d ' ' -f 3 | cut -d ',' -f 1
  register: docker_output

- debug: msg="Docker version installed = {{ docker_output.stdout }}"

- name: Chek docker compatible versions
  set_fact:
    docker_install: false
  when: "'1.11.' in docker_output.stdout or '1.12.' in docker_output.stdout or '1.13.' in docker_output.stdout or '17.03.' in docker_output.stdout or '18.06.' in docker_output.stdout or '18.09.' in docker_output.stdout or '19.03.' in docker_output.stdout"

- name: Install docker
  include_tasks: "{{ansible_os_family}}_docker.yaml"

- name: Create /etc/docker/daemon.json
  register: docker_json
  copy:
    content: "{{ docker_options | to_nice_json(indent=2) }}"
    dest: /etc/docker/daemon.json

- name: restart docker
  service:
    name: docker
    state: restarted
    enabled: yes
  when: docker_json is changed
