  - name: Add Helm repo
    command: helm repo add {{ helm_repo_name }} {{ helm_repo_url }}
    environment:
      KUBECONFIG: "{{KUBECONFIG}}"

  - name: Set empty extra args
    set_fact:
      extra_args: ""

  - name: Set values file arg
    set_fact:
      extra_args: "{{ extra_args }} -f {{ helm_values_file }}"
    when: helm_values_file is defined and helm_values_file != ""

  - name: Set chart version arg {{ helm_chart_version }}
    set_fact:
      extra_args: "{{ extra_args }} --version={{ helm_chart_version }}"
    when: helm_chart_version is defined and helm_chart_version != "latest"

  - name: Set wait arg
    set_fact:
      extra_args: "{{ extra_args }} --wait"
    when: helm_wait is defined and helm_wait
  
  - name: Set timeout arg
    set_fact:
      extra_args: "{{ extra_args }} --timeout {{ helm_timeout }}"
    when: helm_timeout is defined

  - name: Check if {{ helm_chart_name }} is installed
    command: helm status {{ helm_chart_name }} -n {{ helm_chart_namespace }}
    environment:
      KUBECONFIG: "{{KUBECONFIG}}"
    register: helm_status
    ignore_errors: yes
    changed_when: false

  - block:

    - name: Install {{ helm_chart_name }} {{ helm_chart_version }}
      command: helm upgrade {{ helm_chart_name }} --install --namespace {{ helm_chart_namespace }} --create-namespace {{ helm_repo_name }}/{{ helm_chart_name }} {{ extra_args }}
      environment:
        KUBECONFIG: "{{KUBECONFIG}}"
      async: 900
      poll: 5
      ignore_errors: true
      register: helm_install

    - name: Undeploy {{ helm_chart_name }} app
      command: helm uninstall --namespace {{ helm_chart_namespace }} {{ helm_chart_name }}
      when: helm_install is failed

    - name: Undeploy {{ helm_app_name }} app
      fail:
        msg: "Error installing {{ helm_app_name }} helm chat"
      when: helm_install is failed

    when: helm_status.rc != 0
