---
  - name: Add Kyverno Helm repo
    command: helm repo add kyverno https://kyverno.github.io/kyverno/
    environment:
      KUBECONFIG: "{{KUBECONFIG}}"

  - name: Check if kyverno is installed
    command: helm status kyverno -n kyverno
    register: helm_status
    ignore_errors: yes
    changed_when: false

  - name: Check if kyverno-crds is installed
    command: helm status kyverno-crds -n kyverno
    register: helm_status_kyverno_crds
    ignore_errors: yes
    changed_when: false

  - name: Helm update
    command: helm repo update
    environment:
      KUBECONFIG: "{{KUBECONFIG}}"

  - name: Create namespace kyverno 
    command: kubectl create namespace kyverno
    environment:
      KUBECONFIG: "{{KUBECONFIG}}"
    when: helm_status.rc != 0

  - name: Install kyverno-crds {{kyverno_crds_helm_chart_version}}
    command: helm install kyverno-crds kyverno/kyverno-crds --namespace kyverno --version={{kyverno_crds_helm_chart_version}}
    environment:
      KUBECONFIG: "{{KUBECONFIG}}"
    when: helm_status_kyverno_crds.rc != 0
  
  - template: src=kyverno-values.j2 dest=/tmp/kyverno-values.yml

  - name: Install kyverno {{kyverno_helm_chart_version}}
    command: helm install kyverno --namespace kyverno -f /tmp/kyverno-values.yml kyverno/kyverno --version={{kyverno_helm_chart_version}}
    environment:
      KUBECONFIG: "{{KUBECONFIG}}"
    when: helm_status.rc != 0