- name: Create longhorn-csi-values.yaml
  copy:
    content: |
      defaultSettings:
        defaultDataPath: {{ longhorn_default_data_path }}
      persistence:
        reclaimPolicy: {{ longhorn_reclaim_policy }}
        defaultClassReplicaCount: {{ longhorn_num_replicas }}
      ingress:
        enabled: false
    dest: /var/tmp/longhorn-csi-values.yaml

- name: Install longhorn helm chart
  import_tasks: helm_chart.yaml
  vars:
    helm_chart_name: longhorn
    helm_chart_namespace: longhorn-system
    helm_repo_name: longhorn
    helm_repo_url: https://charts.longhorn.io
    helm_chart_version: "{{ kube_longhorn_chart_version }}"
    helm_wait: false
    helm_values_file: /var/tmp/longhorn-csi-values.yaml

- name: Create longhorn-ingress.yaml
  template: src=longhorn-ingress.j2 dest=/tmp/longhorn-ingress.yaml
  when: kube_install_longhorn_ingress | bool

- name: Apply longhorn-ingress.yaml
  command: kubectl apply -f /tmp/longhorn-ingress.yaml
  environment:
    KUBECONFIG: "{{KUBECONFIG}}"
  when: kube_install_longhorn_ingress | bool