- name: Create ingress-values.yaml
  copy:
    content: |
      persistence:
        defaultClass: {{ 'true' if longhorn_set_default else 'false' }}
        reclaimPolicy: {{ longhorn_reclaim_policy }}
        defaultClassReplicaCount: {{ longhorn_replica_count }}
      ingress:
        ingressClassName: nginx
        enabled: {{ 'true' if longhorn_ingress_enabled else 'false' }}
        annotations:
          nginx.ingress.kubernetes.io/auth-secret: basic-auth
    dest: /var/tmp/longhorn-csi-values.yaml

- name: Install ingress-nginx helm chart
  import_tasks: helm_chart.yaml
  vars:
    helm_chart_name: longhorn
    helm_chart_namespace: longhorn-system
    helm_repo_name: longhorn
    helm_repo_url: https://charts.longhorn.io
    helm_chart_version: "{{ kube_longhorn_chart_version }}"
    helm_wait: false
    helm_values_file: /var/tmp/longhorn-csi-values.yaml

- name: Create basic-auth secret for longhorn ingress
  copy:
    content: |
      apiVersion: v1
      kind: Secret
      type: Opaque
      metadata:
        name: basic-auth
        namespace: longhorn-system
      data:
        auth: {{ kube_longhorn_ingress_auth | b64encode }}
    dest: /var/tmp/longhorn-auth.yaml

- name: Apply longhorn-auth.yaml
  command: kubectl apply -f /var/tmp/longhorn-auth.yaml
  environment:
    KUBECONFIG: "{{KUBECONFIG}}"
