---
- name: Download nvidia-container-runtime yum repo
  get_url:
    url: https://nvidia.github.io/nvidia-container-runtime/{{ansible_distribution | lower}}{{ansible_distribution_version}}/nvidia-container-runtime.repo
    dest: /etc/yum.repos.d/nvidia-container-runtime.repo

- name: Add nvidia repo key
  rpm_key:
    state: present
    key: https://nvidia.github.io/nvidia-container-runtime/gpgkey

- name: Install nvidia-container-runtime  package
  yum: name=nvidia-container-runtime 
  notify: restart containerd

- name: Change runtime to nvidia-container-runtime
  lineinfile:
    path: /etc/containerd/config.toml
    regexp: '^(.*)runtime = "runc"(.*)$'
    line: '\1runtime = "nvidia-container-runtime"\2'
    backrefs: yes
  notify: restart containerd
