---

# In CentOS we must assume that drivers are already installed
- name: Check nvidia is installed
  stat:
    path: /var/lib/dkms/nvidia
  register: nvidia_inst

- fail:
    msg: It seems that NVIDIA drivers are not installed.
  when: not (nvidia_inst.stat.isdir is defined and nvidia_inst.stat.isdir)

- block:

    - name: Download nvidia-docker yum repo
      get_url:
        url: https://nvidia.github.io/nvidia-docker/{{ansible_distribution | lower}}{{ansible_distribution_version}}/nvidia-docker.repo
        dest: /etc/yum.repos.d/nvidia-docker.repo

    - name: Add nvidia repo key
      rpm_key:
        state: present
        key: https://nvidia.github.io/nvidia-docker/gpgkey

    - name: Install nvidia-docker2 package
      yum: name=nvidia-docker2
      notify: restart docker

    - copy:
        dest: /etc/docker/daemon.json
        content: |
            {
                "storage-driver": "devicemapper",
                "default-runtime": "nvidia",
                "runtimes": {
                    "nvidia": {
                        "path": "/usr/bin/nvidia-container-runtime",
                        "runtimeArgs": []
                    }
                }
            }
      notify: restart docker

  when: kube_cri_runtime == "docker"


- block:

    - name: Download nvidia-container-runtime yum repo
      get_url:
        url: https://nvidia.github.io/nvidia-container-runtime/{{ansible_distribution | lower}}{{ansible_distribution_version}}/nvidia-container-runtime.repo
        dest: /etc/yum.repos.d/nvidia-container-runtime.repo

    - name: Add nvidia repo key
      rpm_key:
        state: present
        key: https://nvidia.github.io/nvidia-container-runtime/gpgkey

    - name: Install nvidia-container-runtime  package
      yum: name=nvidia-container-runtime 
      notify: restart containerd

    - name: Change runtime to nvidia-container-runtime
      lineinfile:
        path: /etc/containerd/config.toml
        regexp: '^(.*)runtime = "runc"(.*)$'
        line: '\1runtime = "nvidia-container-runtime"\2'
        backrefs: yes
      notify: restart containerd

  when: kube_cri_runtime == "containerd"