---
# In CentOS we must assume that drivers are already installed
- name: Check nvidia is installed
  stat:
    path: /var/lib/dkms/nvidia
  register: nvidia_inst

- fail:
    msg: It seems that NVIDIA drivers are not installed.
  when: not (nvidia_inst.stat.isdir is defined and nvidia_inst.stat.isdir)

- name: Include NVIDIA {{kube_cri_runtime}} tasks
  include_tasks: "RedHat_nvidia_{{kube_cri_runtime}}.yaml"
