---
- name: Install Requisites
  yum: name=device-mapper-persistent-data,lvm2 state=installed

- name: Download docker-ce.repo
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo

- name: Install containerd.io
  register: containerd_installed
  yum: name=containerd.io state=installed update_cache=yes

- name: Delete initial /etc/containerd/config.toml file
  file:
    path: /etc/containerd/config.toml
    state: absent
  when: containerd_installed is changed