---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: "network"
value: 1000000000
preemptionPolicy: PreemptLowerPriority
globalDefault: false
description: "Ensure Cilium pods have high priority to prevent any unexpected eviction by the Kubernetes scheduler under node pressure"
