#!/bin/bash

LINES=`ps aux | grep "ansible" | grep -v "\[mux\]" | wc -l`
docker inspect im > /dev/null 2> /dev/null

if [ $LINES -gt 1 -o "$?" -ne "0" ]
then
        echo "Cluster is still configuring."
else
        echo "Cluster configured!"
fi
